# Generated by Django 5.2 on 2025-12-29 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_order_status_cart_cart_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='status',
            field=models.CharField(choices=[('inprogress', 'inprogress'), ('completed', 'completed')], max_length=120),
        ),
    ]
