# Generated by Django 5.2 on 2025-12-24 13:46

import datetime
import taggit.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='review',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 12, 24, 13, 46, 6, 505716, tzinfo=datetime.timezone.utc)),
        ),
    ]
