# Generated by Django 5.2 on 2025-12-29 11:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_review_publish_date_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 12, 29, 11, 38, 31, 542807, tzinfo=datetime.timezone.utc)),
        ),
    ]
