# Generated by Django 5.2 on 2025-12-29 12:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_review_publish_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 12, 29, 12, 41, 32, 615369, tzinfo=datetime.timezone.utc)),
        ),
    ]
