# Generated by Django 5.2 on 2025-12-29 13:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_review_publish_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 12, 29, 13, 37, 15, 628642, tzinfo=datetime.timezone.utc)),
        ),
    ]
